#!/usr/bin/env bash
pwd

BIBTEX_FILE="$1"

KEYS_TO_REMOVE="
 file
 abstract
 doi
 issn
 keywords
 langid
 eprint
 eprinttype
"

for KEY in $KEYS_TO_REMOVE; do
  sed -i -E "/$KEY = \{/d"  "$BIBTEX_FILE"
done
