#!/usr/bin/env bash

BIBTEX_FILE="$1"

TMP_FILE="$(mktemp)"

KEYS_TO_REMOVE="
 file
 abstract
 doi
 issn
 keywords
 langid
 eprint
 eprinttype
"

cat $BIBTEX_FILE > $TMP_FILE

for KEY in $KEYS_TO_REMOVE; do
  sed -i -E "/$KEY = \{/d"  "$TMP_FILE"
done

diff $BIBTEX_FILE $TMP_FILE

cat $TMP_FILE > $BIBTEX_FILE

rm $TMP_FILE
